### ISSUE TITLE
Only XMRig shows up as an option

### ISSUE THREAD

**Issue by thepwrtank18** [LITdevs/SaladBind#128]
## Description
I have a 3060 Ti, no limiter. This shouldn't happen.

~~Bypassing GPU checks does nothing.~~ The issue is fixable by bypassing GPU checks, then restarting SaladBind.

## How to reproduce
* Reconfigure SaladBind via 1.7.3 update
* Try to mine
* See only XMRig

![image](https://user-images.githubusercontent.com/57580668/144694908-30ec4118-02a3-43b1-9c99-cee3b3542b83.png)

**Comment by vtheskeleton** [comment]
Hello, Could you please launch SaladBind with the `-d` argument and provide us the debug data it gives you.

Thanks

**Comment by thepwrtank18** [comment]
Doing `-d` crashes SaladBind.
```
Could not write debug (no permissions?). Here's some debug data:
{
  err: "Error: ENOENT: no such file or directory, open 'C:\\Users\\Leo\\AppData\\Local\\SaladBind\\Log/saladbind-debug.txt'\n" +
    '    at Object.openSync (node:fs:585:3)\n' +
    '    at Object.openSync (pkg/prelude/bootstrap.js:739:32)\n' +
    '    at Object.writeFileSync (node:fs:2153:35)\n' +
    '    at Object.<anonymous> (C:\\snapshot\\SaladBind\\src\\index.js)\n' +
    '    at Module._compile (pkg/prelude/bootstrap.js:1794:22)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
    '    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)\n' +
    '    at node:internal/main/run_main_module:17:47',
  debug: {
    timestamp: 1638638818446,
    configured: true,
    __dirname: 'C:\\snapshot\\SaladBind\\src',
    cwd: 'C:\\Users\\Leo\\Desktop',
    version: '1.7.3',
    config: {
      id: '792cc9e4-e7d4-42ec-b316-0d8842524986',
      minerId: 'oerzs9dxdi0qv9l',
      discordPresence: true,
      bypassGPUChecks: true
    },
    discordRPC: { connected: false, user: undefined },
    platform: 'Windows ( 10.0.22000)',
    system: '  ',
    miners: 'T-Rex-0.24.7',
    last: {
      algo: 'ethash',
      pool: [Object],
      region: 'us',
      data: [Object],
      advancedCommands: ''
    },
    gpus: []
  }
}
```

**Comment by vtheskeleton** [comment]
odd..
seems like it didnt pick up any gpu info

**Comment by Vukkyy** [comment]
I swear we added a handler for this, then SOMEONE removed it

**Comment by thepwrtank18** [comment]
lmao

**Comment by skyline69** [comment]
same error

**Comment by EaGamesInc** [comment]
if you get that error it means youall are gay

**Comment by Kief5555** [comment]
Same error | Mac

**Comment by Vukkyy** [comment]
> Same error | Mac

If you are using MacOS, that is not an error. No miners (except for XMRig) support MacOS at the moment.

**Comment by vtheskeleton** [comment]
> XMRig (GPU) for macOS exists (search it up!)

It does yes, but we dont support xmrig gpu at all
